const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map();let files=[],picked=0,played=[],removed=[];
const node=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',style:{},setAttribute(){},focus(){},classList:{toggle(){}}});return nodes.get(s)};
const listeners={},storage=new Map([['aether-preview-v1',JSON.stringify({favorites:[0,1],slots:[{game:0,id:1}]})]]);
const ctx={document:{querySelector:node,querySelectorAll:()=>[],addEventListener:(k,f)=>listeners[k]=f,body:{classList:{toggle(){}}}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setInterval(){},setTimeout(){},clearTimeout(){},queueMicrotask(){},AndroidLibrary:{getLibrary:()=>JSON.stringify(files),chooseGames:()=>picked++,play:id=>played.push(id),remove:id=>removed.push(id),openEmulator(){}},console};ctx.window=ctx;ctx.scrollTo=()=>{};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../../platforms/android/app/src/main/assets/index.html'),'utf8').split('<script>')[1].split('</script>')[0],ctx);
assert.match(node('#main').innerHTML,/Your games start here/);
assert.doesNotMatch(node('#main').innerHTML,/God of War|Shadow of the Colossus/);
vm.runInContext('actions.add()',ctx);assert.equal(picked,1);
files=[{id:17,title:'My <disc> & game',filename:'My <disc> & game.iso',size:2147483648,added:1720000000000,lastLaunch:0}];
ctx.refreshLibrary();assert.match(node('#main').innerHTML,/My &lt;disc&gt; &amp; game/);assert.match(node('#main').innerHTML,/2.00 GB/);
vm.runInContext('actions.play()',ctx);assert.deepEqual(played,[17]);
vm.runInContext('actions.favorite();page="library";filter="Favorites";render()',ctx);assert.match(node('#main').innerHTML,/data-game="17"/);
vm.runInContext('actions.favorite();page="library";render()',ctx);assert.match(node('#main').innerHTML,/No favorites yet/);
vm.runInContext('page="details";render()',ctx);assert.match(node('#main').innerHTML,/Not opened yet/);assert.doesNotMatch(node('#main').innerHTML,/hours played|Sample.*Playable/);
listeners.click({target:{closest:()=>({dataset:{remove:'17'}})}});assert.deepEqual(removed,[17]);
files=[];ctx.refreshLibrary();assert.match(node('#main').innerHTML,/Your games start here/);
console.log('PASS: empty library, picker dispatch, actual-file rendering, filename escaping, size, launch ID, favorites, removal dispatch, empty state after removal.');
let coverDownloads=0,coverChoices=[],automatic=[];
ctx.AndroidLibrary.downloadCovers=()=>coverDownloads++;
ctx.AndroidLibrary.chooseCover=id=>coverChoices.push(id);
ctx.AndroidLibrary.setAutomaticCovers=value=>automatic.push(value);
files=[{id:17,title:'My disc',filename:'My disc.iso',size:2147483648,added:1720000000000,lastLaunch:0,coverAvailable:true,coverSerial:'SLUS-20915',coverState:'Downloaded',coverUrl:'https://covers.aether.local/SLUS-20915.jpg?v=1'}];
ctx.refreshLibrary();vm.runInContext('page="home";render()',ctx);
assert.match(node('#main').innerHTML,/class="cover has-art"/);
assert.match(node('#main').innerHTML,/https:\/\/covers\.aether\.local\/SLUS-20915\.jpg/);
vm.runInContext('actions.downloadcovers();actions.choosecover();actions.autocovers()',ctx);
assert.equal(coverDownloads,1);assert.deepEqual(coverChoices,[17]);assert.deepEqual(automatic,[false]);
vm.runInContext('modal="search-dialog"',ctx);ctx.refreshCoverLibrary();assert.equal(vm.runInContext('modal',ctx),'search-dialog');
console.log('PASS: cached cover rendering, download request, manual matching dispatch, automatic toggle, asynchronous cover update preserves modal.');
let songEnabled=true,trackingRequests=0,infoRequests=0,autoInfoEnabled=true,sourceRequests=[];
ctx.AndroidLibrary.themeEnabled=()=>songEnabled;ctx.AndroidLibrary.setThemeEnabled=value=>songEnabled=value;
ctx.AndroidLibrary.trackingAccess=()=>true;ctx.AndroidLibrary.trackingStatus=()=> 'Ready to track';ctx.AndroidLibrary.enableTracking=()=>trackingRequests++;
ctx.AndroidLibrary.automaticInfo=()=>autoInfoEnabled;ctx.AndroidLibrary.setAutomaticInfo=value=>autoInfoEnabled=value;
ctx.AndroidLibrary.downloadInfo=()=>infoRequests++;ctx.AndroidLibrary.openInfoSource=id=>sourceRequests.push(id);
vm.runInContext('modal="";actions.theme();page="settings";render();actions.tracking();actions.downloadinfo();actions.autoinfo()',ctx);
assert.equal(songEnabled,false);assert.equal(trackingRequests,1);assert.equal(infoRequests,1);assert.equal(autoInfoEnabled,false);
assert.match(node('#main').innerHTML,/Black Ice/);
assert.match(node('#main').innerHTML,/aria-label="Black Ice Theme" aria-checked="false"/);
files[0].playMs=3720000;files[0].lastSessionMs=120000;files[0].description='A <game> from the database.';files[0].gamePublisher='Studio & Co';
ctx.refreshLibrary();vm.runInContext('page="details";render();actions.infosource()',ctx);
assert.match(node('#main').innerHTML,/1h 2m/);assert.match(node('#main').innerHTML,/2 min/);
assert.match(node('#main').innerHTML,/A &lt;game&gt; from the database/);assert.match(node('#main').innerHTML,/Studio &amp; Co/);assert.deepEqual(sourceRequests,[17]);
assert.equal(vm.runInContext('duration(0)',ctx),'0 min');assert.equal(vm.runInContext('duration(5000)',ctx),'< 1 min');
console.log('PASS: Black Ice identity, music toggle, tracking setup dispatch, metadata download/automatic toggle, description escaping/source link, and playtime formatting.');
node('#playlist-name').value='  Weekend   <favorites>  ';
vm.runInContext('savePlaylist()',ctx);
assert.equal(vm.runInContext('playlists.length',ctx),1);
assert.equal(vm.runInContext('playlists[0].name',ctx),'Weekend <favorites>');
assert.match(node('#layers').innerHTML,/Weekend &lt;favorites&gt;/);
vm.runInContext('toggleMember(playlistById(),17);toggleMember(playlistById(),999);actions.doneplaylist()',ctx);
assert.match(node('#main').innerHTML,/data-game="17"/);
assert.equal(vm.runInContext('playlists[0].games.length',ctx),1);
node('#playlist-name').value='Weekend <favorites>';vm.runInContext('savePlaylist()',ctx);
assert.equal(vm.runInContext('playlists.length',ctx),1);
node('#playlist-name').value='Evening';vm.runInContext('savePlaylist(true)',ctx);
assert.equal(vm.runInContext('playlists[0].name',ctx),'Evening');
assert.equal(JSON.parse(storage.get('aether-library-v2')).playlists[0].games[0],17);
vm.runInContext('toggleMember(playlistById(),17);render()',ctx);
assert.match(node('#main').innerHTML,/This playlist is empty/);
vm.runInContext('actions.confirmdeleteplaylist()',ctx);
assert.equal(vm.runInContext('playlists.length',ctx),0);assert.equal(files.length,1);
let levels=[],sfx=[];ctx.AndroidLibrary.setThemeVolume=v=>levels.push(v);ctx.AndroidLibrary.uiSound=k=>sfx.push(k);
listeners.input({target:{id:'music-volume',value:'8'}});assert.deepEqual(levels,[8]);
listeners.click({target:{closest:()=>({dataset:{page:'home'}})}});
assert.equal(vm.runInContext('page',ctx),'home');assert.deepEqual(sfx,['click']);
listeners.change({target:{id:'sort',value:'title'}});assert.equal(JSON.parse(storage.get('aether-library-v2')).prefs.sort,'title');
console.log('PASS: playlist create/duplicate prevention/rename/delete, valid membership, persistence, escaping, empty collection, Home click, sound dispatch, volume and remembered sort.');
let appended,appInert=false,removedSplash=false;
node('.brand svg').outerHTML='<svg viewBox="0 0 100 104"></svg>';
node('.app').setAttribute=()=>appInert=true;node('.app').removeAttribute=()=>appInert=false;
ctx.document.createElement=()=>({setAttribute(){},querySelector:()=>({focus(){}})});
ctx.document.body.appendChild=el=>{appended=el;nodes.set('#startup',{remove(){removedSplash=true}})};
ctx.matchMedia=()=>({matches:false});
vm.runInContext('prefs.startup=true;prefs.reduced=false;startAnimation()',ctx);
assert.equal(appInert,true);assert.match(appended.innerHTML,/svg.*BLACK ICE/);
ctx.androidControl('select');assert.equal(removedSplash,true);assert.equal(appInert,false);
assert.equal(vm.runInContext('startupActive',ctx),false);
vm.runInContext('prefs.reduced=true;startAnimation()',ctx);assert.equal(vm.runInContext('startupActive',ctx),false);
console.log('PASS: logo startup overlay, controller skip, focus unlock, reduced-motion bypass.');
